version: '2.1'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka-broker:
        image: wurstmeister/kafka:2.12-2.0.1
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka-broker"
            HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://127.0.0.1:9092}
        depends_on:
            - zookeeper
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    jobmanager:
        image: pyflink-image/develop:test
        build:
            context: ""
        restart: always
        volumes:
            - ./examples:/opt/examples
        hostname: "jobmanager"
        expose:
            - "6123"
        ports:
            - "8088:8088"
        command: jobmanager
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
    taskmanager:
        image: pyflink-image/develop:test
        volumes:
            - ./examples:/opt/examples
        expose:
            - "6121"
            - "6122"
        depends_on:
            - jobmanager
        command: taskmanager
        links:
            - jobmanager:jobmanager
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
